name: reusable npm package publisher

on:
  workflow_call:
    inputs:
      package_dir:
        description: The relative path to the package root directory.
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        description: The NPM_TOKEN to use for publishing. For more on Reusable Workflows, Secrets and Environments see https://github.community/t/reusable-workflows-secrets-and-environments/203695/6
        required: true

jobs:
  publish_package:
    # For more on Reusable Workflows, Secrets and Environments see https://github.community/t/reusable-workflows-secrets-and-environments/203695/6
    environment: npm
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      #- name: debug publish_package
      #  uses: actions/bin/debug@master

      - name: install & build
        run: |
          # NOTE: assuming a monorepo with `npm workspaces` and the workspace package in the repo root 
          #       so installing and building from the root first.
          npm ci
          npm run build --if-present

      - name: publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NOTE: We're expecting this to come from the environment declared on the job
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ${{ inputs.package_dir }}
          npx semantic-release@19
