name: reusable npm package publisher

on:
  workflow_call:
    inputs:
      package_dir:
        description: The relative path to the package root directory.
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        description: A NPM token for publishing to NPM
        required: true

jobs:
  publish_package:
    runs-on: ubuntu-20.04
    # semantic-release will decide from the repo's config whether to release or not. See .releaserc* in the package dir
    #if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha'

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      #- name: debug publish_package
      #  uses: actions/bin/debug@master

      - name: install & build
        run: |
          # NOTE: assuming a monorepo with `npm workspaces` and the workspace package in the repo root 
          #       so installing and building from the root first.
          npm ci
          npm run build

      - name: publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ${{ inputs.package_dir }}
          npx semantic-release@19
