name: pr-auto-merge-labeler

# Reusable way to label PRs with "auto-merge-enabled" tag when a PR has auto-merge enabled and 
# removed when it is disabled.
# The follow help article explains about the Github feature for automatically merging pull requests: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request
#
# EXAMPLE! Use a workflow like the below to run this re-usable workflow:
#
#on:
#  pull_request_target:
#    types: [auto_merge_enabled, auto_merge_disabled]
#
#jobs:
#  label:
#    uses: activescott/github-actions-workflows/.github/workflows/pr-auto-merge-labeler.yml@pr-auto-merge-labeler-v1

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  remove_label:
    if: github.event.pull_request.auto_merge == null
    runs-on: ubuntu-20.04
    steps:
      - uses: hmarr/debug-action@v2

      - uses: actions/github-script@v6
        name: log context
        with:
          script: |
            console.log(JSON.stringify(context))

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabels({
              issue_number: context.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['auto-merge-enabled']
            })

  add_label:
    if: github.event.pull_request.auto_merge
    runs-on: ubuntu-20.04
    steps:
      - uses: hmarr/debug-action@v2

      - uses: actions/github-script@v6
        name: log context
        with:
          script: |
            console.log(JSON.stringify(context))

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['auto-merge-enabled']
            })