on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/**

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: install actionlint
        run: |
          # per https://github.com/rhysd/actionlint/blob/main/docs/install.md
          cd "${GITHUB_WORKSPACE}"
          ls -la
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: check workflows
        run: |
          cd "${GITHUB_WORKSPACE}"
          ls -la
          actionlint --verbose
